### PR TITLE
chore(RHTAPWATCH-173): Remove unecessary Application events

### PR DESCRIPTION
**Pull request by amisstea**
Only Application create events are desired at this time.

### CODE REVIEW

**Review by hmariset — APPROVED** [review]
LGTM

**Review by ifireball — COMMENTED** [review]
Code-wise LGTM, but are we sure we only need Application creation events? 

In the UJ event lsts, application creation in the UI and picking a name are listed separately, are we sure both are a single event in the backend?

**Review by Omeramsc — APPROVED** [review]
LGTM, however I would add in the commit (or change in a separate commit) about all the lint changes. this could've been a much smaller PR

**Comment by amisstea** [comment]
> LGTM, however I would add in the commit (or change in a separate commit) about all the lint changes. this could've been a much smaller PR

I broke this up into two commits rather than trying to alter the default `gofmt` execution in my IDE (vscode).

**Comment by amisstea** [comment]
> Code-wise LGTM, but are we sure we only need Application creation events?
> 
> In the UJ event lists, application creation in the UI and picking a name are listed separately, are we sure both are a single event in the backend?

@ifireball yes, I've confirmed this. It's all part of the same backend event because it's the same as the resource name.

**Pull request merged**
