### PR TITLE
chore(RHTAPWATCH-200): automate dependency updates

### PR DESCRIPTION
**Pull request by Omeramsc**
# Description

Adds a Dependabot to github actions in order to automate dependency updates.

Dependabot will update the following:
- docker (all 3 dockerfiles in the repository)
- gomod (go)
- pip (python)
- github actions

## Issue ticket number and link
[RHTAPWATCH-200](https://issues.redhat.com/browse/RHTAPWATCH-200)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
YAML file was linted, cannot test locally besides in another repo.

# Checklist:

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added meaningful description with JIRA/GitHub issue key (if applicable)
- [ ] I have updated labels (if needed)

### CODE REVIEW

**Review by amisstea — APPROVED** [review]

**Review by ifireball — CHANGES_REQUESTED** [review]
GitHub AFAIK has dependabot integration in the repository settings screen, so I don't think we need to configure an action like this at all.

Also, the file name has a comma in it instead of a dot.

**Comment by Omeramsc** [comment]
> GitHub AFAIK has dependabot integration in the repository settings screen, so I don't think we need to configure an action like this at all.
> 
> Also, the file name has a comma in it instead of a dot.

Any reason not to define it in source control? I think it's better, and allows it to be changed if needed in the future.
for instance, currently you're the only one with permissions to the settings screen.

**Comment by ifireball** [comment]
> > GitHub AFAIK has dependabot integration in the repository settings screen, so I don't think we need to configure an action like this at all.
> > Also, the file name has a comma in it instead of a dot.
> 
> Any reason not to define it in source control? I think it's better, and allows it allows to be changed if needed in the future. for instance, currently you're the only one with permissions to the settings screen.

Yes. Not to maintain code for something we can get for "free".

It seems some configuration can still reside in SCM.

https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot

**Comment by Omeramsc** [comment]
> > > GitHub AFAIK has dependabot integration in the repository settings screen, so I don't think we need to configure an action like this at all.
> > > Also, the file name has a comma in it instead of a dot.
> > 
> > 
> > Any reason not to define it in source control? I think it's better, and allows it allows to be changed if needed in the future. for instance, currently you're the only one with permissions to the settings screen.
> 
> Yes. Not to maintain code for something we can get for "free".
> 
> It seems some configuration can still reside in SCM.
> 
> https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot

I honestly don't see it as a positive thing, at least not as positive as having it in SCM so we can manage and track it. 
but either way, if we want to use GH integration I'll need you to either give me the required (maintainer, I guess) permissions or have you finish the task.

**Comment by ifireball** [comment]
> > > > GitHub AFAIK has dependabot integration in the repository settings screen, so I don't think we need to configure an action like this at all.
> > > > Also, the file name has a comma in it instead of a dot.
> > > 
> > > 
> > > Any reason not to define it in source control? I think it's better, and allows it allows to be changed if needed in the future. for instance, currently you're the only one with permissions to the settings screen.
> > 
> > 
> > Yes. Not to maintain code for something we can get for "free".
> > It seems some configuration can still reside in SCM.
> > https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot
> 
> I honestly don't see it as a positive thing, at least not as positive as having it in SCM so we can manage and track it. but either way, if we want to use GH integration I'll need you to either give me the required (maintainer, I guess) permissions or have you finish the task.

Did you spend any time reading about the Dependabot integration with GitHub? If you look at the following link you'll see you keep all the important setting in the repo, you just don't need to write your own actions for running the bot.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

Please change this PR to add a proper `.github/dependabot.yaml` file. I've already enabled security updates and warnings in the repo settings, but general version updates require adding that file.

**Comment by Omeramsc** [comment]
> > > > > GitHub AFAIK has dependabot integration in the repository settings screen, so I don't think we need to configure an action like this at all.
> > > > > Also, the file name has a comma in it instead of a dot.
> > > > 
> > > > 
> > > > Any reason not to define it in source control? I think it's better, and allows it allows to be changed if needed in the future. for instance, currently you're the only one with permissions to the settings screen.
> > > 
> > > 
> > > Yes. Not to maintain code for something we can get for "free".
> > > It seems some configuration can still reside in SCM.
> > > https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot
> > 
> > 
> > I honestly don't see it as a positive thing, at least not as positive as having it in SCM so we can manage and track it. but either way, if we want to use GH integration I'll need you to either give me the required (maintainer, I guess) permissions or have you finish the task.
> 
> Did you spend any time reading about the Dependabot integration with GitHub? If you look at the following link you'll see you keep all the important setting in the repo, you just don't need to write your own actions for running the bot. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> 
> Please change this PR to add a proper `.github/dependabot.yaml` file. I've already enabled security updates and warnings in the repo settings, but general version updates require adding that file.

I did read it, and I'm honestly not sure what you're talking about. which actions did I write? look at the file in this PR, it's a proper `.github/dependabot.yaml` file, same as mentioned in the link you added...

**Comment by ifireball** [comment]
> > > > GitHub AFAIK has dependabot integration in the repository settings screen, so I don't think we need to configure an action like this at all.
> > > > Also, the file name has a comma in it instead of a dot.
> > > 
> > > 
> > > Any reason not to define it in source control? I think it's better, and allows it allows to be changed if needed in the future. for instance, currently you're the only one with permissions to the settings screen.
> > 
> > 
> > Yes. Not to maintain code for something we can get for "free".
> > It seems some configuration can still reside in SCM.
> > https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot
> 
> I honestly don't see it as a positive thing, at least not as positive as having it in SCM so we can manage and track it. but either way, if we want to use GH integration I'll need you to either give me the required (maintainer, I guess) permissions or have you finish the task.

didn't we have a GitHub action file here as well at some point? My my memory is not what it used to be

**Review by ifireball — APPROVED** [review]

**Pull request merged**
